/*
 * Decompiled with CFR 0.152.
 */
package meridian.protocol;

import meridian.protocol.NetworkChannel;
import meridian.protocol.Packet;
import meridian.protocol.io.ValidationResult;
import meridian.protocol.packets.asseteditor.AssetEditorActivateButton;
import meridian.protocol.packets.asseteditor.AssetEditorAssetListSetup;
import meridian.protocol.packets.asseteditor.AssetEditorAssetListUpdate;
import meridian.protocol.packets.asseteditor.AssetEditorAssetPackSetup;
import meridian.protocol.packets.asseteditor.AssetEditorAssetUpdated;
import meridian.protocol.packets.asseteditor.AssetEditorAuthorization;
import meridian.protocol.packets.asseteditor.AssetEditorCapabilities;
import meridian.protocol.packets.asseteditor.AssetEditorCreateAsset;
import meridian.protocol.packets.asseteditor.AssetEditorCreateAssetPack;
import meridian.protocol.packets.asseteditor.AssetEditorCreateDirectory;
import meridian.protocol.packets.asseteditor.AssetEditorDeleteAsset;
import meridian.protocol.packets.asseteditor.AssetEditorDeleteAssetPack;
import meridian.protocol.packets.asseteditor.AssetEditorDeleteDirectory;
import meridian.protocol.packets.asseteditor.AssetEditorDiscardChanges;
import meridian.protocol.packets.asseteditor.AssetEditorExportAssetFinalize;
import meridian.protocol.packets.asseteditor.AssetEditorExportAssetInitialize;
import meridian.protocol.packets.asseteditor.AssetEditorExportAssetPart;
import meridian.protocol.packets.asseteditor.AssetEditorExportAssets;
import meridian.protocol.packets.asseteditor.AssetEditorExportComplete;
import meridian.protocol.packets.asseteditor.AssetEditorExportDeleteAssets;
import meridian.protocol.packets.asseteditor.AssetEditorFetchAsset;
import meridian.protocol.packets.asseteditor.AssetEditorFetchAssetReply;
import meridian.protocol.packets.asseteditor.AssetEditorFetchAutoCompleteData;
import meridian.protocol.packets.asseteditor.AssetEditorFetchAutoCompleteDataReply;
import meridian.protocol.packets.asseteditor.AssetEditorFetchJsonAssetWithParents;
import meridian.protocol.packets.asseteditor.AssetEditorFetchJsonAssetWithParentsReply;
import meridian.protocol.packets.asseteditor.AssetEditorFetchLastModifiedAssets;
import meridian.protocol.packets.asseteditor.AssetEditorInitialize;
import meridian.protocol.packets.asseteditor.AssetEditorJsonAssetUpdated;
import meridian.protocol.packets.asseteditor.AssetEditorLastModifiedAssets;
import meridian.protocol.packets.asseteditor.AssetEditorModifiedAssetsCount;
import meridian.protocol.packets.asseteditor.AssetEditorModsDirectories;
import meridian.protocol.packets.asseteditor.AssetEditorPopupNotification;
import meridian.protocol.packets.asseteditor.AssetEditorRedoChanges;
import meridian.protocol.packets.asseteditor.AssetEditorRenameAsset;
import meridian.protocol.packets.asseteditor.AssetEditorRenameDirectory;
import meridian.protocol.packets.asseteditor.AssetEditorRequestChildrenList;
import meridian.protocol.packets.asseteditor.AssetEditorRequestChildrenListReply;
import meridian.protocol.packets.asseteditor.AssetEditorRequestDataset;
import meridian.protocol.packets.asseteditor.AssetEditorRequestDatasetReply;
import meridian.protocol.packets.asseteditor.AssetEditorSelectAsset;
import meridian.protocol.packets.asseteditor.AssetEditorSetGameTime;
import meridian.protocol.packets.asseteditor.AssetEditorSetupAssetTypes;
import meridian.protocol.packets.asseteditor.AssetEditorSetupSchemas;
import meridian.protocol.packets.asseteditor.AssetEditorSubscribeModifiedAssetsChanges;
import meridian.protocol.packets.asseteditor.AssetEditorUndoChanges;
import meridian.protocol.packets.asseteditor.AssetEditorUndoRedoReply;
import meridian.protocol.packets.asseteditor.AssetEditorUpdateAsset;
import meridian.protocol.packets.asseteditor.AssetEditorUpdateAssetPack;
import meridian.protocol.packets.asseteditor.AssetEditorUpdateJsonAsset;
import meridian.protocol.packets.asseteditor.AssetEditorUpdateModelPreview;
import meridian.protocol.packets.asseteditor.AssetEditorUpdateSecondsPerGameDay;
import meridian.protocol.packets.asseteditor.AssetEditorUpdateWeatherPreviewLock;
import meridian.protocol.packets.asseteditor.FailureReply;
import meridian.protocol.packets.asseteditor.SuccessReply;
import meridian.protocol.packets.assets.TrackOrUpdateObjective;
import meridian.protocol.packets.assets.UntrackObjective;
import meridian.protocol.packets.assets.UpdateAmbienceFX;
import meridian.protocol.packets.assets.UpdateAudioCategories;
import meridian.protocol.packets.assets.UpdateBlockBreakingDecals;
import meridian.protocol.packets.assets.UpdateBlockGroups;
import meridian.protocol.packets.assets.UpdateBlockHitboxes;
import meridian.protocol.packets.assets.UpdateBlockParticleSets;
import meridian.protocol.packets.assets.UpdateBlockSets;
import meridian.protocol.packets.assets.UpdateBlockSoundSets;
import meridian.protocol.packets.assets.UpdateBlockTypes;
import meridian.protocol.packets.assets.UpdateCameraShake;
import meridian.protocol.packets.assets.UpdateEmotes;
import meridian.protocol.packets.assets.UpdateEntityEffects;
import meridian.protocol.packets.assets.UpdateEntityStatTypes;
import meridian.protocol.packets.assets.UpdateEntityUIComponents;
import meridian.protocol.packets.assets.UpdateEnvironments;
import meridian.protocol.packets.assets.UpdateEqualizerEffects;
import meridian.protocol.packets.assets.UpdateFieldcraftCategories;
import meridian.protocol.packets.assets.UpdateFluidFX;
import meridian.protocol.packets.assets.UpdateFluids;
import meridian.protocol.packets.assets.UpdateHitboxCollisionConfig;
import meridian.protocol.packets.assets.UpdateInteractions;
import meridian.protocol.packets.assets.UpdateItemCategories;
import meridian.protocol.packets.assets.UpdateItemPlayerAnimations;
import meridian.protocol.packets.assets.UpdateItemQualities;
import meridian.protocol.packets.assets.UpdateItemReticles;
import meridian.protocol.packets.assets.UpdateItemSoundSets;
import meridian.protocol.packets.assets.UpdateItems;
import meridian.protocol.packets.assets.UpdateModelvfxs;
import meridian.protocol.packets.assets.UpdateObjectiveTask;
import meridian.protocol.packets.assets.UpdateParticleSpawners;
import meridian.protocol.packets.assets.UpdateParticleSystems;
import meridian.protocol.packets.assets.UpdateProjectileConfigs;
import meridian.protocol.packets.assets.UpdateRecipes;
import meridian.protocol.packets.assets.UpdateRepulsionConfig;
import meridian.protocol.packets.assets.UpdateResourceTypes;
import meridian.protocol.packets.assets.UpdateReverbEffects;
import meridian.protocol.packets.assets.UpdateRootInteractions;
import meridian.protocol.packets.assets.UpdateSoundEvents;
import meridian.protocol.packets.assets.UpdateSoundSets;
import meridian.protocol.packets.assets.UpdateTagPatterns;
import meridian.protocol.packets.assets.UpdateTrails;
import meridian.protocol.packets.assets.UpdateTranslations;
import meridian.protocol.packets.assets.UpdateUnarmedInteractions;
import meridian.protocol.packets.assets.UpdateViewBobbing;
import meridian.protocol.packets.assets.UpdateWeathers;
import meridian.protocol.packets.auth.AuthGrant;
import meridian.protocol.packets.auth.AuthToken;
import meridian.protocol.packets.auth.ClientReferral;
import meridian.protocol.packets.auth.ConnectAccept;
import meridian.protocol.packets.auth.PasswordAccepted;
import meridian.protocol.packets.auth.PasswordRejected;
import meridian.protocol.packets.auth.PasswordResponse;
import meridian.protocol.packets.auth.ServerAuthToken;
import meridian.protocol.packets.buildertools.BuilderToolArgUpdate;
import meridian.protocol.packets.buildertools.BuilderToolEntityAction;
import meridian.protocol.packets.buildertools.BuilderToolExtrudeAction;
import meridian.protocol.packets.buildertools.BuilderToolGeneralAction;
import meridian.protocol.packets.buildertools.BuilderToolHideAnchors;
import meridian.protocol.packets.buildertools.BuilderToolLaserPointer;
import meridian.protocol.packets.buildertools.BuilderToolLineAction;
import meridian.protocol.packets.buildertools.BuilderToolOnUseInteraction;
import meridian.protocol.packets.buildertools.BuilderToolPasteClipboard;
import meridian.protocol.packets.buildertools.BuilderToolResetClipboardRotation;
import meridian.protocol.packets.buildertools.BuilderToolRotateClipboard;
import meridian.protocol.packets.buildertools.BuilderToolSelectionToolAskForClipboard;
import meridian.protocol.packets.buildertools.BuilderToolSelectionToolReplyWithClipboard;
import meridian.protocol.packets.buildertools.BuilderToolSelectionTransform;
import meridian.protocol.packets.buildertools.BuilderToolSelectionUpdate;
import meridian.protocol.packets.buildertools.BuilderToolSetEntityCollision;
import meridian.protocol.packets.buildertools.BuilderToolSetEntityLight;
import meridian.protocol.packets.buildertools.BuilderToolSetEntityPickupEnabled;
import meridian.protocol.packets.buildertools.BuilderToolSetEntityScale;
import meridian.protocol.packets.buildertools.BuilderToolSetEntityTransform;
import meridian.protocol.packets.buildertools.BuilderToolSetNPCDebug;
import meridian.protocol.packets.buildertools.BuilderToolSetTransformationModeState;
import meridian.protocol.packets.buildertools.BuilderToolShowAnchor;
import meridian.protocol.packets.buildertools.BuilderToolStackArea;
import meridian.protocol.packets.buildertools.BuilderToolsSetSoundSet;
import meridian.protocol.packets.buildertools.PrefabSetAnchor;
import meridian.protocol.packets.buildertools.PrefabUnselectPrefab;
import meridian.protocol.packets.camera.CameraShakeEffect;
import meridian.protocol.packets.camera.RequestFlyCameraMode;
import meridian.protocol.packets.camera.SetFlyCameraMode;
import meridian.protocol.packets.camera.SetServerCamera;
import meridian.protocol.packets.connection.ClientDisconnect;
import meridian.protocol.packets.connection.Connect;
import meridian.protocol.packets.connection.Ping;
import meridian.protocol.packets.connection.Pong;
import meridian.protocol.packets.connection.ServerDisconnect;
import meridian.protocol.packets.entities.ApplyKnockback;
import meridian.protocol.packets.entities.ChangeVelocity;
import meridian.protocol.packets.entities.EntityUpdates;
import meridian.protocol.packets.entities.MountMovement;
import meridian.protocol.packets.entities.PlayAnimation;
import meridian.protocol.packets.entities.PlayEmote;
import meridian.protocol.packets.entities.SetEntitySeed;
import meridian.protocol.packets.entities.SpawnModelParticles;
import meridian.protocol.packets.interaction.CancelInteractionChain;
import meridian.protocol.packets.interaction.DismountNPC;
import meridian.protocol.packets.interaction.MountNPC;
import meridian.protocol.packets.interaction.PlayInteractionFor;
import meridian.protocol.packets.interaction.SyncInteractionChains;
import meridian.protocol.packets.interface_.AddToServerPlayerList;
import meridian.protocol.packets.interface_.ChatMessage;
import meridian.protocol.packets.interface_.CustomHud;
import meridian.protocol.packets.interface_.CustomPage;
import meridian.protocol.packets.interface_.CustomPageEvent;
import meridian.protocol.packets.interface_.EditorBlocksChange;
import meridian.protocol.packets.interface_.HideEventTitle;
import meridian.protocol.packets.interface_.KillFeedMessage;
import meridian.protocol.packets.interface_.Notification;
import meridian.protocol.packets.interface_.OpenChatWithCommand;
import meridian.protocol.packets.interface_.RemoveFromServerPlayerList;
import meridian.protocol.packets.interface_.ResetUserInterfaceState;
import meridian.protocol.packets.interface_.ServerInfo;
import meridian.protocol.packets.interface_.ServerMessage;
import meridian.protocol.packets.interface_.SetPage;
import meridian.protocol.packets.interface_.ShowEventTitle;
import meridian.protocol.packets.interface_.UpdateAnchorUI;
import meridian.protocol.packets.interface_.UpdateKnownRecipes;
import meridian.protocol.packets.interface_.UpdateLanguage;
import meridian.protocol.packets.interface_.UpdatePortal;
import meridian.protocol.packets.interface_.UpdateServerPlayerList;
import meridian.protocol.packets.interface_.UpdateServerPlayerListPing;
import meridian.protocol.packets.interface_.UpdateVisibleHudComponents;
import meridian.protocol.packets.interface_.WorldSavingStatus;
import meridian.protocol.packets.inventory.DropCreativeItem;
import meridian.protocol.packets.inventory.DropItemStack;
import meridian.protocol.packets.inventory.InventoryAction;
import meridian.protocol.packets.inventory.MoveItemStack;
import meridian.protocol.packets.inventory.SetActiveSlot;
import meridian.protocol.packets.inventory.SetCreativeItem;
import meridian.protocol.packets.inventory.SmartGiveCreativeItem;
import meridian.protocol.packets.inventory.SmartMoveItemStack;
import meridian.protocol.packets.inventory.SwitchHotbarBlockSet;
import meridian.protocol.packets.inventory.UpdatePlayerInventory;
import meridian.protocol.packets.machinima.RequestMachinimaActorModel;
import meridian.protocol.packets.machinima.SetMachinimaActorModel;
import meridian.protocol.packets.machinima.UpdateMachinimaScene;
import meridian.protocol.packets.player.ClearDebugShapes;
import meridian.protocol.packets.player.ClientMovement;
import meridian.protocol.packets.player.ClientPlaceBlock;
import meridian.protocol.packets.player.ClientReady;
import meridian.protocol.packets.player.ClientTeleport;
import meridian.protocol.packets.player.DamageInfo;
import meridian.protocol.packets.player.DisplayDebug;
import meridian.protocol.packets.player.JoinWorld;
import meridian.protocol.packets.player.LoadHotbar;
import meridian.protocol.packets.player.MouseInteraction;
import meridian.protocol.packets.player.RemoveMapMarker;
import meridian.protocol.packets.player.ReticleEvent;
import meridian.protocol.packets.player.SaveHotbar;
import meridian.protocol.packets.player.SetBlockPlacementOverride;
import meridian.protocol.packets.player.SetClientId;
import meridian.protocol.packets.player.SetGameMode;
import meridian.protocol.packets.player.SetMovementStates;
import meridian.protocol.packets.player.SyncPlayerPreferences;
import meridian.protocol.packets.player.UpdateMemoriesFeatureStatus;
import meridian.protocol.packets.player.UpdateMovementSettings;
import meridian.protocol.packets.serveraccess.RequestServerAccess;
import meridian.protocol.packets.serveraccess.SetServerAccess;
import meridian.protocol.packets.serveraccess.UpdateServerAccess;
import meridian.protocol.packets.setup.AssetFinalize;
import meridian.protocol.packets.setup.AssetInitialize;
import meridian.protocol.packets.setup.AssetPart;
import meridian.protocol.packets.setup.PlayerOptions;
import meridian.protocol.packets.setup.RemoveAssets;
import meridian.protocol.packets.setup.RequestAssets;
import meridian.protocol.packets.setup.RequestCommonAssetsRebuild;
import meridian.protocol.packets.setup.ServerTags;
import meridian.protocol.packets.setup.SetTimeDilation;
import meridian.protocol.packets.setup.SetUpdateRate;
import meridian.protocol.packets.setup.UpdateFeatures;
import meridian.protocol.packets.setup.ViewRadius;
import meridian.protocol.packets.setup.WorldLoadFinished;
import meridian.protocol.packets.setup.WorldLoadProgress;
import meridian.protocol.packets.setup.WorldSettings;
import meridian.protocol.packets.stream.StreamOpen;
import meridian.protocol.packets.stream.StreamOpenResponse;
import meridian.protocol.packets.voice.RelayedVoiceData;
import meridian.protocol.packets.voice.VoiceConfig;
import meridian.protocol.packets.voice.VoiceData;
import meridian.protocol.packets.window.ClientOpenWindow;
import meridian.protocol.packets.window.CloseWindow;
import meridian.protocol.packets.window.OpenWindow;
import meridian.protocol.packets.window.SendWindowAction;
import meridian.protocol.packets.window.UpdateWindow;
import meridian.protocol.packets.world.ClearEditorTimeOverride;
import meridian.protocol.packets.world.PlaySoundEvent2D;
import meridian.protocol.packets.world.PlaySoundEvent3D;
import meridian.protocol.packets.world.PlaySoundEventEntity;
import meridian.protocol.packets.world.PlaySoundEventLocalPlayer;
import meridian.protocol.packets.world.ServerSetBlock;
import meridian.protocol.packets.world.ServerSetBlocks;
import meridian.protocol.packets.world.ServerSetFluid;
import meridian.protocol.packets.world.ServerSetFluids;
import meridian.protocol.packets.world.ServerSetPaused;
import meridian.protocol.packets.world.SetChunk;
import meridian.protocol.packets.world.SetChunkEnvironments;
import meridian.protocol.packets.world.SetChunkHeightmap;
import meridian.protocol.packets.world.SetChunkTintmap;
import meridian.protocol.packets.world.SetFluids;
import meridian.protocol.packets.world.SetPaused;
import meridian.protocol.packets.world.SpawnBlockParticleSystem;
import meridian.protocol.packets.world.SpawnParticleSystem;
import meridian.protocol.packets.world.UnloadChunk;
import meridian.protocol.packets.world.UpdateBlockDamage;
import meridian.protocol.packets.world.UpdateEditorTimeOverride;
import meridian.protocol.packets.world.UpdateEditorWeatherOverride;
import meridian.protocol.packets.world.UpdateEnvironmentMusic;
import meridian.protocol.packets.world.UpdatePostFxSettings;
import meridian.protocol.packets.world.UpdateSleepState;
import meridian.protocol.packets.world.UpdateSunSettings;
import meridian.protocol.packets.world.UpdateTime;
import meridian.protocol.packets.world.UpdateTimeSettings;
import meridian.protocol.packets.world.UpdateWeather;
import meridian.protocol.packets.worldmap.ClearWorldMap;
import meridian.protocol.packets.worldmap.CreateUserMarker;
import meridian.protocol.packets.worldmap.TeleportToWorldMapMarker;
import meridian.protocol.packets.worldmap.TeleportToWorldMapPosition;
import meridian.protocol.packets.worldmap.UpdateWorldMap;
import meridian.protocol.packets.worldmap.UpdateWorldMapSettings;
import meridian.protocol.packets.worldmap.UpdateWorldMapVisible;
import io.netty.buffer.ByteBuf;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.function.BiFunction;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public final class PacketRegistry {
    private static final Map<Integer, PacketInfo> BY_ID = new HashMap<Integer, PacketInfo>();
    private static final Map<Integer, PacketInfo> TO_SERVER_BY_ID = new HashMap<Integer, PacketInfo>();
    private static final Map<Integer, PacketInfo> TO_CLIENT_BY_ID = new HashMap<Integer, PacketInfo>();
    private static final Map<Integer, PacketInfo> BY_ID_UNMODIFIABLE = Collections.unmodifiableMap(BY_ID);
    private static final Map<Class<? extends Packet>, Integer> BY_TYPE = new HashMap<Class<? extends Packet>, Integer>();

    private PacketRegistry() {
    }

    private static void register(PacketDirection direction, NetworkChannel channel, int id, String name, Class<? extends Packet> type, int fixedBlockSize, int maxSize, boolean compressed, BiFunction<ByteBuf, Integer, ValidationResult> validate, BiFunction<ByteBuf, Integer, Packet> deserialize) {
        PacketInfo existing = BY_ID.get(id);
        if (existing != null) {
            throw new IllegalStateException("Duplicate packet ID " + id + ": '" + name + "' conflicts with '" + existing.name() + "'");
        }
        PacketInfo info = new PacketInfo(id, name, channel, type, fixedBlockSize, maxSize, compressed, validate, deserialize);
        switch (direction.ordinal()) {
            case 0: {
                TO_SERVER_BY_ID.put(id, info);
                break;
            }
            case 1: {
                TO_CLIENT_BY_ID.put(id, info);
                break;
            }
            case 2: {
                TO_SERVER_BY_ID.put(id, info);
                TO_CLIENT_BY_ID.put(id, info);
            }
        }
        BY_ID.put(id, info);
        BY_TYPE.put(type, id);
    }

    @Nullable
    public static PacketInfo getToServerPacketById(int id) {
        return TO_SERVER_BY_ID.get(id);
    }

    @Nullable
    public static PacketInfo getToClientPacketById(int id) {
        return TO_CLIENT_BY_ID.get(id);
    }

    @Nullable
    public static Integer getId(Class<? extends Packet> type) {
        return BY_TYPE.get(type);
    }

    @Nonnull
    public static Map<Integer, PacketInfo> all() {
        return BY_ID_UNMODIFIABLE;
    }

    static {
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 0, "Connect", Connect.class, 46, 38013, false, Connect::validateStructure, Connect::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 1, "ClientDisconnect", ClientDisconnect.class, 2, 2, false, ClientDisconnect::validateStructure, ClientDisconnect::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 2, "ServerDisconnect", ServerDisconnect.class, 2, 0x64000000, false, ServerDisconnect::validateStructure, ServerDisconnect::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 3, "Ping", Ping.class, 29, 29, false, Ping::validateStructure, Ping::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 4, "Pong", Pong.class, 20, 20, false, Pong::validateStructure, Pong::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 11, "AuthGrant", AuthGrant.class, 1, 49171, false, AuthGrant::validateStructure, AuthGrant::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 12, "AuthToken", AuthToken.class, 1, 49171, false, AuthToken::validateStructure, AuthToken::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 13, "ServerAuthToken", ServerAuthToken.class, 1, 32851, false, ServerAuthToken::validateStructure, ServerAuthToken::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 14, "ConnectAccept", ConnectAccept.class, 1, 70, false, ConnectAccept::validateStructure, ConnectAccept::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 15, "PasswordResponse", PasswordResponse.class, 1, 70, false, PasswordResponse::validateStructure, PasswordResponse::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 16, "PasswordAccepted", PasswordAccepted.class, 0, 0, false, PasswordAccepted::validateStructure, PasswordAccepted::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 17, "PasswordRejected", PasswordRejected.class, 5, 74, false, PasswordRejected::validateStructure, PasswordRejected::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 18, "ClientReferral", ClientReferral.class, 1, 5141, false, ClientReferral::validateStructure, ClientReferral::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 20, "WorldSettings", WorldSettings.class, 5, 0x64000000, true, WorldSettings::validateStructure, WorldSettings::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 21, "WorldLoadProgress", WorldLoadProgress.class, 9, 0x64000000, false, WorldLoadProgress::validateStructure, WorldLoadProgress::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 22, "WorldLoadFinished", WorldLoadFinished.class, 0, 0, false, WorldLoadFinished::validateStructure, WorldLoadFinished::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 23, "RequestAssets", RequestAssets.class, 1, 0x64000000, true, RequestAssets::validateStructure, RequestAssets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 24, "AssetInitialize", AssetInitialize.class, 4, 2121, false, AssetInitialize::validateStructure, AssetInitialize::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 25, "AssetPart", AssetPart.class, 1, 4096006, true, AssetPart::validateStructure, AssetPart::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 26, "AssetFinalize", AssetFinalize.class, 0, 0, false, AssetFinalize::validateStructure, AssetFinalize::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 27, "RemoveAssets", RemoveAssets.class, 1, 0x64000000, false, RemoveAssets::validateStructure, RemoveAssets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 28, "RequestCommonAssetsRebuild", RequestCommonAssetsRebuild.class, 0, 0, false, RequestCommonAssetsRebuild::validateStructure, RequestCommonAssetsRebuild::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 29, "SetUpdateRate", SetUpdateRate.class, 4, 4, false, SetUpdateRate::validateStructure, SetUpdateRate::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 30, "SetTimeDilation", SetTimeDilation.class, 4, 4, false, SetTimeDilation::validateStructure, SetTimeDilation::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 31, "UpdateFeatures", UpdateFeatures.class, 1, 8192006, false, UpdateFeatures::validateStructure, UpdateFeatures::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 32, "ViewRadius", ViewRadius.class, 4, 4, false, ViewRadius::validateStructure, ViewRadius::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 33, "PlayerOptions", PlayerOptions.class, 1, 327680184, false, PlayerOptions::validateStructure, PlayerOptions::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 34, "ServerTags", ServerTags.class, 1, 0x64000000, false, ServerTags::validateStructure, ServerTags::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 40, "UpdateBlockTypes", UpdateBlockTypes.class, 10, 0x64000000, true, UpdateBlockTypes::validateStructure, UpdateBlockTypes::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 41, "UpdateBlockHitboxes", UpdateBlockHitboxes.class, 6, 0x64000000, true, UpdateBlockHitboxes::validateStructure, UpdateBlockHitboxes::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 42, "UpdateBlockSoundSets", UpdateBlockSoundSets.class, 6, 0x64000000, true, UpdateBlockSoundSets::validateStructure, UpdateBlockSoundSets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 43, "UpdateItemSoundSets", UpdateItemSoundSets.class, 6, 0x64000000, true, UpdateItemSoundSets::validateStructure, UpdateItemSoundSets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 44, "UpdateBlockParticleSets", UpdateBlockParticleSets.class, 2, 0x64000000, true, UpdateBlockParticleSets::validateStructure, UpdateBlockParticleSets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 45, "UpdateBlockBreakingDecals", UpdateBlockBreakingDecals.class, 2, 0x64000000, true, UpdateBlockBreakingDecals::validateStructure, UpdateBlockBreakingDecals::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 46, "UpdateBlockSets", UpdateBlockSets.class, 2, 0x64000000, true, UpdateBlockSets::validateStructure, UpdateBlockSets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 47, "UpdateWeathers", UpdateWeathers.class, 6, 0x64000000, true, UpdateWeathers::validateStructure, UpdateWeathers::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 48, "UpdateTrails", UpdateTrails.class, 2, 0x64000000, true, UpdateTrails::validateStructure, UpdateTrails::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 49, "UpdateParticleSystems", UpdateParticleSystems.class, 2, 0x64000000, true, UpdateParticleSystems::validateStructure, UpdateParticleSystems::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 50, "UpdateParticleSpawners", UpdateParticleSpawners.class, 2, 0x64000000, true, UpdateParticleSpawners::validateStructure, UpdateParticleSpawners::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 51, "UpdateEntityEffects", UpdateEntityEffects.class, 6, 0x64000000, true, UpdateEntityEffects::validateStructure, UpdateEntityEffects::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 52, "UpdateItemPlayerAnimations", UpdateItemPlayerAnimations.class, 2, 0x64000000, true, UpdateItemPlayerAnimations::validateStructure, UpdateItemPlayerAnimations::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 53, "UpdateModelvfxs", UpdateModelvfxs.class, 6, 0x64000000, true, UpdateModelvfxs::validateStructure, UpdateModelvfxs::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 54, "UpdateItems", UpdateItems.class, 4, 0x64000000, true, UpdateItems::validateStructure, UpdateItems::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 55, "UpdateItemQualities", UpdateItemQualities.class, 6, 0x64000000, true, UpdateItemQualities::validateStructure, UpdateItemQualities::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 56, "UpdateItemCategories", UpdateItemCategories.class, 2, 0x64000000, true, UpdateItemCategories::validateStructure, UpdateItemCategories::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 57, "UpdateItemReticles", UpdateItemReticles.class, 6, 0x64000000, true, UpdateItemReticles::validateStructure, UpdateItemReticles::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 58, "UpdateFieldcraftCategories", UpdateFieldcraftCategories.class, 2, 0x64000000, true, UpdateFieldcraftCategories::validateStructure, UpdateFieldcraftCategories::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 59, "UpdateResourceTypes", UpdateResourceTypes.class, 2, 0x64000000, true, UpdateResourceTypes::validateStructure, UpdateResourceTypes::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 60, "UpdateRecipes", UpdateRecipes.class, 2, 0x64000000, true, UpdateRecipes::validateStructure, UpdateRecipes::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 61, "UpdateEnvironments", UpdateEnvironments.class, 7, 0x64000000, true, UpdateEnvironments::validateStructure, UpdateEnvironments::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 62, "UpdateAmbienceFX", UpdateAmbienceFX.class, 6, 0x64000000, true, UpdateAmbienceFX::validateStructure, UpdateAmbienceFX::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 63, "UpdateFluidFX", UpdateFluidFX.class, 6, 0x64000000, true, UpdateFluidFX::validateStructure, UpdateFluidFX::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 64, "UpdateTranslations", UpdateTranslations.class, 2, 0x64000000, true, UpdateTranslations::validateStructure, UpdateTranslations::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 65, "UpdateSoundEvents", UpdateSoundEvents.class, 6, 0x64000000, true, UpdateSoundEvents::validateStructure, UpdateSoundEvents::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 66, "UpdateInteractions", UpdateInteractions.class, 6, 0x64000000, true, UpdateInteractions::validateStructure, UpdateInteractions::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 67, "UpdateRootInteractions", UpdateRootInteractions.class, 6, 0x64000000, true, UpdateRootInteractions::validateStructure, UpdateRootInteractions::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 68, "UpdateUnarmedInteractions", UpdateUnarmedInteractions.class, 2, 20480007, true, UpdateUnarmedInteractions::validateStructure, UpdateUnarmedInteractions::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 69, "TrackOrUpdateObjective", TrackOrUpdateObjective.class, 1, 0x64000000, false, TrackOrUpdateObjective::validateStructure, TrackOrUpdateObjective::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 70, "UntrackObjective", UntrackObjective.class, 16, 16, false, UntrackObjective::validateStructure, UntrackObjective::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 71, "UpdateObjectiveTask", UpdateObjectiveTask.class, 21, 0x64000000, false, UpdateObjectiveTask::validateStructure, UpdateObjectiveTask::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 72, "UpdateEntityStatTypes", UpdateEntityStatTypes.class, 6, 0x64000000, true, UpdateEntityStatTypes::validateStructure, UpdateEntityStatTypes::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 73, "UpdateEntityUIComponents", UpdateEntityUIComponents.class, 6, 0x64000000, true, UpdateEntityUIComponents::validateStructure, UpdateEntityUIComponents::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 74, "UpdateHitboxCollisionConfig", UpdateHitboxCollisionConfig.class, 6, 36864011, true, UpdateHitboxCollisionConfig::validateStructure, UpdateHitboxCollisionConfig::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 75, "UpdateRepulsionConfig", UpdateRepulsionConfig.class, 6, 65536011, true, UpdateRepulsionConfig::validateStructure, UpdateRepulsionConfig::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 76, "UpdateViewBobbing", UpdateViewBobbing.class, 2, 0x64000000, true, UpdateViewBobbing::validateStructure, UpdateViewBobbing::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 77, "UpdateCameraShake", UpdateCameraShake.class, 2, 0x64000000, true, UpdateCameraShake::validateStructure, UpdateCameraShake::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 78, "UpdateBlockGroups", UpdateBlockGroups.class, 2, 0x64000000, true, UpdateBlockGroups::validateStructure, UpdateBlockGroups::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 79, "UpdateSoundSets", UpdateSoundSets.class, 6, 0x64000000, true, UpdateSoundSets::validateStructure, UpdateSoundSets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 80, "UpdateAudioCategories", UpdateAudioCategories.class, 6, 0x64000000, true, UpdateAudioCategories::validateStructure, UpdateAudioCategories::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 81, "UpdateReverbEffects", UpdateReverbEffects.class, 6, 0x64000000, true, UpdateReverbEffects::validateStructure, UpdateReverbEffects::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 82, "UpdateEqualizerEffects", UpdateEqualizerEffects.class, 6, 0x64000000, true, UpdateEqualizerEffects::validateStructure, UpdateEqualizerEffects::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 83, "UpdateFluids", UpdateFluids.class, 6, 0x64000000, true, UpdateFluids::validateStructure, UpdateFluids::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 84, "UpdateTagPatterns", UpdateTagPatterns.class, 6, 0x64000000, true, UpdateTagPatterns::validateStructure, UpdateTagPatterns::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 85, "UpdateProjectileConfigs", UpdateProjectileConfigs.class, 2, 0x64000000, true, UpdateProjectileConfigs::validateStructure, UpdateProjectileConfigs::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 86, "UpdateEmotes", UpdateEmotes.class, 6, 0x64000000, true, UpdateEmotes::validateStructure, UpdateEmotes::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 100, "SetClientId", SetClientId.class, 4, 4, false, SetClientId::validateStructure, SetClientId::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 101, "SetGameMode", SetGameMode.class, 1, 1, false, SetGameMode::validateStructure, SetGameMode::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 102, "SetMovementStates", SetMovementStates.class, 2, 2, false, SetMovementStates::validateStructure, SetMovementStates::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 103, "SetBlockPlacementOverride", SetBlockPlacementOverride.class, 1, 1, false, SetBlockPlacementOverride::validateStructure, SetBlockPlacementOverride::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 104, "JoinWorld", JoinWorld.class, 18, 18, false, JoinWorld::validateStructure, JoinWorld::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 105, "ClientReady", ClientReady.class, 2, 2, false, ClientReady::validateStructure, ClientReady::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 106, "LoadHotbar", LoadHotbar.class, 1, 1, false, LoadHotbar::validateStructure, LoadHotbar::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 107, "SaveHotbar", SaveHotbar.class, 1, 1, false, SaveHotbar::validateStructure, SaveHotbar::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 108, "ClientMovement", ClientMovement.class, 155, 155, false, ClientMovement::validateStructure, ClientMovement::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 109, "ClientTeleport", ClientTeleport.class, 52, 52, false, ClientTeleport::validateStructure, ClientTeleport::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 110, "UpdateMovementSettings", UpdateMovementSettings.class, 252, 252, false, UpdateMovementSettings::validateStructure, UpdateMovementSettings::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 111, "MouseInteraction", MouseInteraction.class, 44, 20480071, false, MouseInteraction::validateStructure, MouseInteraction::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 112, "DamageInfo", DamageInfo.class, 29, 32768048, false, DamageInfo::validateStructure, DamageInfo::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 113, "ReticleEvent", ReticleEvent.class, 4, 4, false, ReticleEvent::validateStructure, ReticleEvent::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 114, "DisplayDebug", DisplayDebug.class, 23, 32768041, false, DisplayDebug::validateStructure, DisplayDebug::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 115, "ClearDebugShapes", ClearDebugShapes.class, 0, 0, false, ClearDebugShapes::validateStructure, ClearDebugShapes::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 116, "SyncPlayerPreferences", SyncPlayerPreferences.class, 12, 12, false, SyncPlayerPreferences::validateStructure, SyncPlayerPreferences::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 117, "ClientPlaceBlock", ClientPlaceBlock.class, 21, 21, false, ClientPlaceBlock::validateStructure, ClientPlaceBlock::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 118, "UpdateMemoriesFeatureStatus", UpdateMemoriesFeatureStatus.class, 1, 1, false, UpdateMemoriesFeatureStatus::validateStructure, UpdateMemoriesFeatureStatus::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 119, "RemoveMapMarker", RemoveMapMarker.class, 1, 16384006, false, RemoveMapMarker::validateStructure, RemoveMapMarker::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 131, "SetChunk", SetChunk.class, 13, 12288040, true, SetChunk::validateStructure, SetChunk::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 132, "SetChunkHeightmap", SetChunkHeightmap.class, 9, 4096014, true, SetChunkHeightmap::validateStructure, SetChunkHeightmap::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 133, "SetChunkTintmap", SetChunkTintmap.class, 9, 4096014, true, SetChunkTintmap::validateStructure, SetChunkTintmap::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 134, "SetChunkEnvironments", SetChunkEnvironments.class, 9, 4096014, true, SetChunkEnvironments::validateStructure, SetChunkEnvironments::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 135, "UnloadChunk", UnloadChunk.class, 8, 8, false, UnloadChunk::validateStructure, UnloadChunk::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 136, "SetFluids", SetFluids.class, 13, 4096018, true, SetFluids::validateStructure, SetFluids::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 140, "ServerSetBlock", ServerSetBlock.class, 19, 19, false, ServerSetBlock::validateStructure, ServerSetBlock::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 141, "ServerSetBlocks", ServerSetBlocks.class, 12, 36864017, false, ServerSetBlocks::validateStructure, ServerSetBlocks::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 142, "ServerSetFluid", ServerSetFluid.class, 17, 17, false, ServerSetFluid::validateStructure, ServerSetFluid::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 143, "ServerSetFluids", ServerSetFluids.class, 12, 28672017, false, ServerSetFluids::validateStructure, ServerSetFluids::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Chunks, 144, "UpdateBlockDamage", UpdateBlockDamage.class, 21, 21, false, UpdateBlockDamage::validateStructure, UpdateBlockDamage::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 145, "UpdateTimeSettings", UpdateTimeSettings.class, 10, 10, false, UpdateTimeSettings::validateStructure, UpdateTimeSettings::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 146, "UpdateTime", UpdateTime.class, 13, 13, false, UpdateTime::validateStructure, UpdateTime::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 147, "UpdateEditorTimeOverride", UpdateEditorTimeOverride.class, 14, 14, false, UpdateEditorTimeOverride::validateStructure, UpdateEditorTimeOverride::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 148, "ClearEditorTimeOverride", ClearEditorTimeOverride.class, 0, 0, false, ClearEditorTimeOverride::validateStructure, ClearEditorTimeOverride::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 149, "UpdateWeather", UpdateWeather.class, 8, 8, false, UpdateWeather::validateStructure, UpdateWeather::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 150, "UpdateEditorWeatherOverride", UpdateEditorWeatherOverride.class, 4, 4, false, UpdateEditorWeatherOverride::validateStructure, UpdateEditorWeatherOverride::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 151, "UpdateEnvironmentMusic", UpdateEnvironmentMusic.class, 4, 4, false, UpdateEnvironmentMusic::validateStructure, UpdateEnvironmentMusic::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 152, "SpawnParticleSystem", SpawnParticleSystem.class, 44, 16384049, false, SpawnParticleSystem::validateStructure, SpawnParticleSystem::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 153, "SpawnBlockParticleSystem", SpawnBlockParticleSystem.class, 30, 30, false, SpawnBlockParticleSystem::validateStructure, SpawnBlockParticleSystem::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 154, "PlaySoundEvent2D", PlaySoundEvent2D.class, 13, 13, false, PlaySoundEvent2D::validateStructure, PlaySoundEvent2D::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 155, "PlaySoundEvent3D", PlaySoundEvent3D.class, 38, 38, false, PlaySoundEvent3D::validateStructure, PlaySoundEvent3D::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 156, "PlaySoundEventEntity", PlaySoundEventEntity.class, 16, 16, false, PlaySoundEventEntity::validateStructure, PlaySoundEventEntity::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 157, "UpdateSleepState", UpdateSleepState.class, 36, 65536050, false, UpdateSleepState::validateStructure, UpdateSleepState::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 158, "SetPaused", SetPaused.class, 1, 1, false, SetPaused::validateStructure, SetPaused::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 159, "ServerSetPaused", ServerSetPaused.class, 1, 1, false, ServerSetPaused::validateStructure, ServerSetPaused::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 160, "SetEntitySeed", SetEntitySeed.class, 4, 4, false, SetEntitySeed::validateStructure, SetEntitySeed::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 161, "EntityUpdates", EntityUpdates.class, 1, 0x64000000, true, EntityUpdates::validateStructure, EntityUpdates::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 162, "PlayAnimation", PlayAnimation.class, 6, 32768024, false, PlayAnimation::validateStructure, PlayAnimation::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 163, "ChangeVelocity", ChangeVelocity.class, 35, 35, false, ChangeVelocity::validateStructure, ChangeVelocity::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 164, "ApplyKnockback", ApplyKnockback.class, 38, 38, false, ApplyKnockback::validateStructure, ApplyKnockback::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 165, "SpawnModelParticles", SpawnModelParticles.class, 5, 0x64000000, false, SpawnModelParticles::validateStructure, SpawnModelParticles::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 166, "MountMovement", MountMovement.class, 60, 60, false, MountMovement::validateStructure, MountMovement::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 167, "PlayEmote", PlayEmote.class, 1, 16384006, false, PlayEmote::validateStructure, PlayEmote::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 170, "UpdatePlayerInventory", UpdatePlayerInventory.class, 1, 0x64000000, true, UpdatePlayerInventory::validateStructure, UpdatePlayerInventory::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 171, "SetCreativeItem", SetCreativeItem.class, 9, 16384019, false, SetCreativeItem::validateStructure, SetCreativeItem::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 172, "DropCreativeItem", DropCreativeItem.class, 0, 0xFA000A, false, DropCreativeItem::validateStructure, DropCreativeItem::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 173, "SmartGiveCreativeItem", SmartGiveCreativeItem.class, 1, 16384011, false, SmartGiveCreativeItem::validateStructure, SmartGiveCreativeItem::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 174, "DropItemStack", DropItemStack.class, 12, 12, false, DropItemStack::validateStructure, DropItemStack::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 175, "MoveItemStack", MoveItemStack.class, 20, 20, false, MoveItemStack::validateStructure, MoveItemStack::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 176, "SmartMoveItemStack", SmartMoveItemStack.class, 13, 13, false, SmartMoveItemStack::validateStructure, SmartMoveItemStack::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 177, "SetActiveSlot", SetActiveSlot.class, 8, 8, false, SetActiveSlot::validateStructure, SetActiveSlot::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 178, "SwitchHotbarBlockSet", SwitchHotbarBlockSet.class, 1, 16384006, false, SwitchHotbarBlockSet::validateStructure, SwitchHotbarBlockSet::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 179, "InventoryAction", InventoryAction.class, 6, 6, false, InventoryAction::validateStructure, InventoryAction::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 200, "OpenWindow", OpenWindow.class, 6, 0x64000000, true, OpenWindow::validateStructure, OpenWindow::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 201, "UpdateWindow", UpdateWindow.class, 5, 0x64000000, true, UpdateWindow::validateStructure, UpdateWindow::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 202, "CloseWindow", CloseWindow.class, 4, 4, false, CloseWindow::validateStructure, CloseWindow::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 203, "SendWindowAction", SendWindowAction.class, 4, 32768027, false, SendWindowAction::validateStructure, SendWindowAction::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 204, "ClientOpenWindow", ClientOpenWindow.class, 1, 1, false, ClientOpenWindow::validateStructure, ClientOpenWindow::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 210, "ServerMessage", ServerMessage.class, 2, 0x64000000, false, ServerMessage::validateStructure, ServerMessage::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 211, "ChatMessage", ChatMessage.class, 1, 1026, false, ChatMessage::validateStructure, ChatMessage::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 212, "Notification", Notification.class, 2, 0x64000000, false, Notification::validateStructure, Notification::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 213, "KillFeedMessage", KillFeedMessage.class, 1, 0x64000000, false, KillFeedMessage::validateStructure, KillFeedMessage::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 214, "ShowEventTitle", ShowEventTitle.class, 14, 0x64000000, false, ShowEventTitle::validateStructure, ShowEventTitle::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 215, "HideEventTitle", HideEventTitle.class, 4, 4, false, HideEventTitle::validateStructure, HideEventTitle::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 216, "SetPage", SetPage.class, 2, 2, false, SetPage::validateStructure, SetPage::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 217, "CustomHud", CustomHud.class, 2, 0x64000000, true, CustomHud::validateStructure, CustomHud::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 218, "CustomPage", CustomPage.class, 4, 0x64000000, true, CustomPage::validateStructure, CustomPage::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 219, "CustomPageEvent", CustomPageEvent.class, 2, 16384007, false, CustomPageEvent::validateStructure, CustomPageEvent::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 222, "EditorBlocksChange", EditorBlocksChange.class, 31, 0x64000000, true, EditorBlocksChange::validateStructure, EditorBlocksChange::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 223, "ServerInfo", ServerInfo.class, 5, 32769058, false, ServerInfo::validateStructure, ServerInfo::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 224, "AddToServerPlayerList", AddToServerPlayerList.class, 1, 0x64000000, false, AddToServerPlayerList::validateStructure, AddToServerPlayerList::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 225, "RemoveFromServerPlayerList", RemoveFromServerPlayerList.class, 1, 65536006, false, RemoveFromServerPlayerList::validateStructure, RemoveFromServerPlayerList::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 226, "UpdateServerPlayerList", UpdateServerPlayerList.class, 1, 131072006, false, UpdateServerPlayerList::validateStructure, UpdateServerPlayerList::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 227, "UpdateServerPlayerListPing", UpdateServerPlayerListPing.class, 1, 81920006, false, UpdateServerPlayerListPing::validateStructure, UpdateServerPlayerListPing::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 228, "UpdateKnownRecipes", UpdateKnownRecipes.class, 1, 0x64000000, false, UpdateKnownRecipes::validateStructure, UpdateKnownRecipes::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 229, "UpdatePortal", UpdatePortal.class, 6, 16384020, false, UpdatePortal::validateStructure, UpdatePortal::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 230, "UpdateVisibleHudComponents", UpdateVisibleHudComponents.class, 1, 4096006, false, UpdateVisibleHudComponents::validateStructure, UpdateVisibleHudComponents::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 231, "ResetUserInterfaceState", ResetUserInterfaceState.class, 0, 0, false, ResetUserInterfaceState::validateStructure, ResetUserInterfaceState::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 232, "UpdateLanguage", UpdateLanguage.class, 1, 16384006, false, UpdateLanguage::validateStructure, UpdateLanguage::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 233, "WorldSavingStatus", WorldSavingStatus.class, 1, 1, false, WorldSavingStatus::validateStructure, WorldSavingStatus::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 234, "OpenChatWithCommand", OpenChatWithCommand.class, 1, 16384006, false, OpenChatWithCommand::validateStructure, OpenChatWithCommand::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 235, "UpdateAnchorUI", UpdateAnchorUI.class, 2, 0x64000000, true, UpdateAnchorUI::validateStructure, UpdateAnchorUI::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 240, "UpdateWorldMapSettings", UpdateWorldMapSettings.class, 20, 0x64000000, false, UpdateWorldMapSettings::validateStructure, UpdateWorldMapSettings::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.WorldMap, 241, "UpdateWorldMap", UpdateWorldMap.class, 1, 0x64000000, true, UpdateWorldMap::validateStructure, UpdateWorldMap::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.WorldMap, 242, "ClearWorldMap", ClearWorldMap.class, 0, 0, false, ClearWorldMap::validateStructure, ClearWorldMap::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 243, "UpdateWorldMapVisible", UpdateWorldMapVisible.class, 1, 1, false, UpdateWorldMapVisible::validateStructure, UpdateWorldMapVisible::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 244, "TeleportToWorldMapMarker", TeleportToWorldMapMarker.class, 1, 16384006, false, TeleportToWorldMapMarker::validateStructure, TeleportToWorldMapMarker::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 245, "TeleportToWorldMapPosition", TeleportToWorldMapPosition.class, 8, 8, false, TeleportToWorldMapPosition::validateStructure, TeleportToWorldMapPosition::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 246, "CreateUserMarker", CreateUserMarker.class, 13, 32768031, false, CreateUserMarker::validateStructure, CreateUserMarker::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 250, "RequestServerAccess", RequestServerAccess.class, 3, 3, false, RequestServerAccess::validateStructure, RequestServerAccess::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 251, "UpdateServerAccess", UpdateServerAccess.class, 2, 0x64000000, false, UpdateServerAccess::validateStructure, UpdateServerAccess::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 252, "SetServerAccess", SetServerAccess.class, 2, 16384007, false, SetServerAccess::validateStructure, SetServerAccess::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 260, "RequestMachinimaActorModel", RequestMachinimaActorModel.class, 1, 49152028, false, RequestMachinimaActorModel::validateStructure, RequestMachinimaActorModel::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 261, "SetMachinimaActorModel", SetMachinimaActorModel.class, 1, 0x64000000, false, SetMachinimaActorModel::validateStructure, SetMachinimaActorModel::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 262, "UpdateMachinimaScene", UpdateMachinimaScene.class, 6, 36864033, true, UpdateMachinimaScene::validateStructure, UpdateMachinimaScene::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 280, "SetServerCamera", SetServerCamera.class, 157, 157, false, SetServerCamera::validateStructure, SetServerCamera::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 281, "CameraShakeEffect", CameraShakeEffect.class, 9, 9, false, CameraShakeEffect::validateStructure, CameraShakeEffect::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 282, "RequestFlyCameraMode", RequestFlyCameraMode.class, 1, 1, false, RequestFlyCameraMode::validateStructure, RequestFlyCameraMode::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 283, "SetFlyCameraMode", SetFlyCameraMode.class, 1, 1, false, SetFlyCameraMode::validateStructure, SetFlyCameraMode::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 290, "SyncInteractionChains", SyncInteractionChains.class, 0, 0x64000000, false, SyncInteractionChains::validateStructure, SyncInteractionChains::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 291, "CancelInteractionChain", CancelInteractionChain.class, 5, 1038, false, CancelInteractionChain::validateStructure, CancelInteractionChain::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 292, "PlayInteractionFor", PlayInteractionFor.class, 19, 16385065, false, PlayInteractionFor::validateStructure, PlayInteractionFor::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 293, "MountNPC", MountNPC.class, 16, 16, false, MountNPC::validateStructure, MountNPC::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 294, "DismountNPC", DismountNPC.class, 0, 0, false, DismountNPC::validateStructure, DismountNPC::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 300, "FailureReply", FailureReply.class, 5, 0x64000000, false, FailureReply::validateStructure, FailureReply::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 301, "SuccessReply", SuccessReply.class, 5, 0x64000000, false, SuccessReply::validateStructure, SuccessReply::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 302, "AssetEditorInitialize", AssetEditorInitialize.class, 0, 0, false, AssetEditorInitialize::validateStructure, AssetEditorInitialize::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 303, "AssetEditorAuthorization", AssetEditorAuthorization.class, 1, 1, false, AssetEditorAuthorization::validateStructure, AssetEditorAuthorization::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 304, "AssetEditorCapabilities", AssetEditorCapabilities.class, 5, 5, false, AssetEditorCapabilities::validateStructure, AssetEditorCapabilities::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 305, "AssetEditorSetupSchemas", AssetEditorSetupSchemas.class, 1, 0x64000000, true, AssetEditorSetupSchemas::validateStructure, AssetEditorSetupSchemas::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 306, "AssetEditorSetupAssetTypes", AssetEditorSetupAssetTypes.class, 1, 0x64000000, false, AssetEditorSetupAssetTypes::validateStructure, AssetEditorSetupAssetTypes::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 307, "AssetEditorCreateDirectory", AssetEditorCreateDirectory.class, 5, 32768024, false, AssetEditorCreateDirectory::validateStructure, AssetEditorCreateDirectory::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 308, "AssetEditorDeleteDirectory", AssetEditorDeleteDirectory.class, 5, 32768024, false, AssetEditorDeleteDirectory::validateStructure, AssetEditorDeleteDirectory::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 309, "AssetEditorRenameDirectory", AssetEditorRenameDirectory.class, 5, 65536051, false, AssetEditorRenameDirectory::validateStructure, AssetEditorRenameDirectory::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 310, "AssetEditorFetchAsset", AssetEditorFetchAsset.class, 6, 32768025, false, AssetEditorFetchAsset::validateStructure, AssetEditorFetchAsset::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 311, "AssetEditorFetchJsonAssetWithParents", AssetEditorFetchJsonAssetWithParents.class, 6, 32768025, false, AssetEditorFetchJsonAssetWithParents::validateStructure, AssetEditorFetchJsonAssetWithParents::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 312, "AssetEditorFetchAssetReply", AssetEditorFetchAssetReply.class, 5, 4096010, false, AssetEditorFetchAssetReply::validateStructure, AssetEditorFetchAssetReply::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 313, "AssetEditorFetchJsonAssetWithParentsReply", AssetEditorFetchJsonAssetWithParentsReply.class, 5, 0x64000000, true, AssetEditorFetchJsonAssetWithParentsReply::validateStructure, AssetEditorFetchJsonAssetWithParentsReply::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 314, "AssetEditorAssetPackSetup", AssetEditorAssetPackSetup.class, 1, 0x64000000, false, AssetEditorAssetPackSetup::validateStructure, AssetEditorAssetPackSetup::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 315, "AssetEditorUpdateAssetPack", AssetEditorUpdateAssetPack.class, 1, 0x64000000, false, AssetEditorUpdateAssetPack::validateStructure, AssetEditorUpdateAssetPack::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 316, "AssetEditorCreateAssetPack", AssetEditorCreateAssetPack.class, 9, 0x64000000, false, AssetEditorCreateAssetPack::validateStructure, AssetEditorCreateAssetPack::deserialize);
        PacketRegistry.register(PacketDirection.Both, NetworkChannel.Default, 317, "AssetEditorDeleteAssetPack", AssetEditorDeleteAssetPack.class, 1, 16384006, false, AssetEditorDeleteAssetPack::validateStructure, AssetEditorDeleteAssetPack::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 319, "AssetEditorAssetListSetup", AssetEditorAssetListSetup.class, 4, 0x64000000, true, AssetEditorAssetListSetup::validateStructure, AssetEditorAssetListSetup::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 320, "AssetEditorAssetListUpdate", AssetEditorAssetListUpdate.class, 1, 0x64000000, true, AssetEditorAssetListUpdate::validateStructure, AssetEditorAssetListUpdate::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 321, "AssetEditorRequestChildrenList", AssetEditorRequestChildrenList.class, 1, 32768020, false, AssetEditorRequestChildrenList::validateStructure, AssetEditorRequestChildrenList::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 322, "AssetEditorRequestChildrenListReply", AssetEditorRequestChildrenListReply.class, 1, 0x64000000, false, AssetEditorRequestChildrenListReply::validateStructure, AssetEditorRequestChildrenListReply::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 323, "AssetEditorUpdateJsonAsset", AssetEditorUpdateJsonAsset.class, 9, 0x64000000, true, AssetEditorUpdateJsonAsset::validateStructure, AssetEditorUpdateJsonAsset::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 324, "AssetEditorUpdateAsset", AssetEditorUpdateAsset.class, 9, 53248050, false, AssetEditorUpdateAsset::validateStructure, AssetEditorUpdateAsset::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 325, "AssetEditorJsonAssetUpdated", AssetEditorJsonAssetUpdated.class, 1, 0x64000000, false, AssetEditorJsonAssetUpdated::validateStructure, AssetEditorJsonAssetUpdated::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 326, "AssetEditorAssetUpdated", AssetEditorAssetUpdated.class, 1, 36864033, false, AssetEditorAssetUpdated::validateStructure, AssetEditorAssetUpdated::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 327, "AssetEditorCreateAsset", AssetEditorCreateAsset.class, 10, 53248051, false, AssetEditorCreateAsset::validateStructure, AssetEditorCreateAsset::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 328, "AssetEditorRenameAsset", AssetEditorRenameAsset.class, 5, 65536051, false, AssetEditorRenameAsset::validateStructure, AssetEditorRenameAsset::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 329, "AssetEditorDeleteAsset", AssetEditorDeleteAsset.class, 5, 32768024, false, AssetEditorDeleteAsset::validateStructure, AssetEditorDeleteAsset::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 330, "AssetEditorDiscardChanges", AssetEditorDiscardChanges.class, 1, 0x64000000, false, AssetEditorDiscardChanges::validateStructure, AssetEditorDiscardChanges::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 331, "AssetEditorFetchAutoCompleteData", AssetEditorFetchAutoCompleteData.class, 5, 32768023, false, AssetEditorFetchAutoCompleteData::validateStructure, AssetEditorFetchAutoCompleteData::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 332, "AssetEditorFetchAutoCompleteDataReply", AssetEditorFetchAutoCompleteDataReply.class, 5, 0x64000000, false, AssetEditorFetchAutoCompleteDataReply::validateStructure, AssetEditorFetchAutoCompleteDataReply::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 333, "AssetEditorRequestDataset", AssetEditorRequestDataset.class, 1, 16384006, false, AssetEditorRequestDataset::validateStructure, AssetEditorRequestDataset::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 334, "AssetEditorRequestDatasetReply", AssetEditorRequestDatasetReply.class, 1, 0x64000000, false, AssetEditorRequestDatasetReply::validateStructure, AssetEditorRequestDatasetReply::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 335, "AssetEditorActivateButton", AssetEditorActivateButton.class, 1, 16384006, false, AssetEditorActivateButton::validateStructure, AssetEditorActivateButton::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 336, "AssetEditorSelectAsset", AssetEditorSelectAsset.class, 1, 32768020, false, AssetEditorSelectAsset::validateStructure, AssetEditorSelectAsset::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 337, "AssetEditorPopupNotification", AssetEditorPopupNotification.class, 2, 0x64000000, false, AssetEditorPopupNotification::validateStructure, AssetEditorPopupNotification::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 338, "AssetEditorFetchLastModifiedAssets", AssetEditorFetchLastModifiedAssets.class, 0, 0, false, AssetEditorFetchLastModifiedAssets::validateStructure, AssetEditorFetchLastModifiedAssets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 339, "AssetEditorLastModifiedAssets", AssetEditorLastModifiedAssets.class, 1, 0x64000000, false, AssetEditorLastModifiedAssets::validateStructure, AssetEditorLastModifiedAssets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 340, "AssetEditorModifiedAssetsCount", AssetEditorModifiedAssetsCount.class, 4, 4, false, AssetEditorModifiedAssetsCount::validateStructure, AssetEditorModifiedAssetsCount::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 341, "AssetEditorSubscribeModifiedAssetsChanges", AssetEditorSubscribeModifiedAssetsChanges.class, 1, 1, false, AssetEditorSubscribeModifiedAssetsChanges::validateStructure, AssetEditorSubscribeModifiedAssetsChanges::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 342, "AssetEditorExportAssets", AssetEditorExportAssets.class, 1, 0x64000000, false, AssetEditorExportAssets::validateStructure, AssetEditorExportAssets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 343, "AssetEditorExportAssetInitialize", AssetEditorExportAssetInitialize.class, 6, 81920066, false, AssetEditorExportAssetInitialize::validateStructure, AssetEditorExportAssetInitialize::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 344, "AssetEditorExportAssetPart", AssetEditorExportAssetPart.class, 1, 4096006, true, AssetEditorExportAssetPart::validateStructure, AssetEditorExportAssetPart::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 345, "AssetEditorExportAssetFinalize", AssetEditorExportAssetFinalize.class, 0, 0, false, AssetEditorExportAssetFinalize::validateStructure, AssetEditorExportAssetFinalize::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 346, "AssetEditorExportDeleteAssets", AssetEditorExportDeleteAssets.class, 1, 0x64000000, false, AssetEditorExportDeleteAssets::validateStructure, AssetEditorExportDeleteAssets::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 347, "AssetEditorExportComplete", AssetEditorExportComplete.class, 1, 0x64000000, false, AssetEditorExportComplete::validateStructure, AssetEditorExportComplete::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 349, "AssetEditorUndoChanges", AssetEditorUndoChanges.class, 5, 32768024, false, AssetEditorUndoChanges::validateStructure, AssetEditorUndoChanges::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 350, "AssetEditorRedoChanges", AssetEditorRedoChanges.class, 5, 32768024, false, AssetEditorRedoChanges::validateStructure, AssetEditorRedoChanges::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 351, "AssetEditorUndoRedoReply", AssetEditorUndoRedoReply.class, 5, 0x64000000, false, AssetEditorUndoRedoReply::validateStructure, AssetEditorUndoRedoReply::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 352, "AssetEditorSetGameTime", AssetEditorSetGameTime.class, 14, 14, false, AssetEditorSetGameTime::validateStructure, AssetEditorSetGameTime::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 353, "AssetEditorUpdateSecondsPerGameDay", AssetEditorUpdateSecondsPerGameDay.class, 8, 8, false, AssetEditorUpdateSecondsPerGameDay::validateStructure, AssetEditorUpdateSecondsPerGameDay::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 354, "AssetEditorUpdateWeatherPreviewLock", AssetEditorUpdateWeatherPreviewLock.class, 1, 1, false, AssetEditorUpdateWeatherPreviewLock::validateStructure, AssetEditorUpdateWeatherPreviewLock::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 355, "AssetEditorUpdateModelPreview", AssetEditorUpdateModelPreview.class, 30, 0x64000000, false, AssetEditorUpdateModelPreview::validateStructure, AssetEditorUpdateModelPreview::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 356, "AssetEditorModsDirectories", AssetEditorModsDirectories.class, 1, 0x64000000, false, AssetEditorModsDirectories::validateStructure, AssetEditorModsDirectories::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 360, "UpdateSunSettings", UpdateSunSettings.class, 8, 8, false, UpdateSunSettings::validateStructure, UpdateSunSettings::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 361, "UpdatePostFxSettings", UpdatePostFxSettings.class, 20, 20, false, UpdatePostFxSettings::validateStructure, UpdatePostFxSettings::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 362, "PlaySoundEventLocalPlayer", PlaySoundEventLocalPlayer.class, 17, 17, false, PlaySoundEventLocalPlayer::validateStructure, PlaySoundEventLocalPlayer::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 400, "BuilderToolArgUpdate", BuilderToolArgUpdate.class, 13, 32768031, false, BuilderToolArgUpdate::validateStructure, BuilderToolArgUpdate::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 401, "BuilderToolEntityAction", BuilderToolEntityAction.class, 5, 5, false, BuilderToolEntityAction::validateStructure, BuilderToolEntityAction::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 402, "BuilderToolSetEntityTransform", BuilderToolSetEntityTransform.class, 54, 54, false, BuilderToolSetEntityTransform::validateStructure, BuilderToolSetEntityTransform::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 403, "BuilderToolExtrudeAction", BuilderToolExtrudeAction.class, 24, 24, false, BuilderToolExtrudeAction::validateStructure, BuilderToolExtrudeAction::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 404, "BuilderToolStackArea", BuilderToolStackArea.class, 41, 41, false, BuilderToolStackArea::validateStructure, BuilderToolStackArea::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 405, "BuilderToolSelectionTransform", BuilderToolSelectionTransform.class, 80, 80, false, BuilderToolSelectionTransform::validateStructure, BuilderToolSelectionTransform::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 406, "BuilderToolRotateClipboard", BuilderToolRotateClipboard.class, 5, 5, false, BuilderToolRotateClipboard::validateStructure, BuilderToolRotateClipboard::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 407, "BuilderToolPasteClipboard", BuilderToolPasteClipboard.class, 12, 12, false, BuilderToolPasteClipboard::validateStructure, BuilderToolPasteClipboard::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 408, "BuilderToolSetTransformationModeState", BuilderToolSetTransformationModeState.class, 1, 1, false, BuilderToolSetTransformationModeState::validateStructure, BuilderToolSetTransformationModeState::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 409, "BuilderToolSelectionUpdate", BuilderToolSelectionUpdate.class, 24, 24, false, BuilderToolSelectionUpdate::validateStructure, BuilderToolSelectionUpdate::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 410, "BuilderToolSelectionToolAskForClipboard", BuilderToolSelectionToolAskForClipboard.class, 0, 0, false, BuilderToolSelectionToolAskForClipboard::validateStructure, BuilderToolSelectionToolAskForClipboard::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 411, "BuilderToolSelectionToolReplyWithClipboard", BuilderToolSelectionToolReplyWithClipboard.class, 1, 0x64000000, true, BuilderToolSelectionToolReplyWithClipboard::validateStructure, BuilderToolSelectionToolReplyWithClipboard::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 412, "BuilderToolGeneralAction", BuilderToolGeneralAction.class, 1, 1, false, BuilderToolGeneralAction::validateStructure, BuilderToolGeneralAction::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 413, "BuilderToolOnUseInteraction", BuilderToolOnUseInteraction.class, 61, 61, false, BuilderToolOnUseInteraction::validateStructure, BuilderToolOnUseInteraction::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 414, "BuilderToolLineAction", BuilderToolLineAction.class, 24, 24, false, BuilderToolLineAction::validateStructure, BuilderToolLineAction::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 415, "BuilderToolShowAnchor", BuilderToolShowAnchor.class, 12, 12, false, BuilderToolShowAnchor::validateStructure, BuilderToolShowAnchor::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 416, "BuilderToolHideAnchors", BuilderToolHideAnchors.class, 0, 0, false, BuilderToolHideAnchors::validateStructure, BuilderToolHideAnchors::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 417, "PrefabUnselectPrefab", PrefabUnselectPrefab.class, 0, 0, false, PrefabUnselectPrefab::validateStructure, PrefabUnselectPrefab::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 418, "BuilderToolsSetSoundSet", BuilderToolsSetSoundSet.class, 4, 4, false, BuilderToolsSetSoundSet::validateStructure, BuilderToolsSetSoundSet::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 419, "BuilderToolLaserPointer", BuilderToolLaserPointer.class, 36, 36, false, BuilderToolLaserPointer::validateStructure, BuilderToolLaserPointer::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 420, "BuilderToolSetEntityScale", BuilderToolSetEntityScale.class, 8, 8, false, BuilderToolSetEntityScale::validateStructure, BuilderToolSetEntityScale::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 421, "BuilderToolSetEntityPickupEnabled", BuilderToolSetEntityPickupEnabled.class, 5, 5, false, BuilderToolSetEntityPickupEnabled::validateStructure, BuilderToolSetEntityPickupEnabled::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 422, "BuilderToolSetEntityLight", BuilderToolSetEntityLight.class, 9, 9, false, BuilderToolSetEntityLight::validateStructure, BuilderToolSetEntityLight::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 423, "BuilderToolSetNPCDebug", BuilderToolSetNPCDebug.class, 5, 5, false, BuilderToolSetNPCDebug::validateStructure, BuilderToolSetNPCDebug::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 425, "BuilderToolSetEntityCollision", BuilderToolSetEntityCollision.class, 5, 0xFA000A, false, BuilderToolSetEntityCollision::validateStructure, BuilderToolSetEntityCollision::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 426, "PrefabSetAnchor", PrefabSetAnchor.class, 12, 12, false, PrefabSetAnchor::validateStructure, PrefabSetAnchor::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 427, "BuilderToolResetClipboardRotation", BuilderToolResetClipboardRotation.class, 0, 0, false, BuilderToolResetClipboardRotation::validateStructure, BuilderToolResetClipboardRotation::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Voice, 450, "VoiceData", VoiceData.class, 6, 523, false, VoiceData::validateStructure, VoiceData::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Voice, 451, "RelayedVoiceData", RelayedVoiceData.class, 52, 569, false, RelayedVoiceData::validateStructure, RelayedVoiceData::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 452, "VoiceConfig", VoiceConfig.class, 17, 17, false, VoiceConfig::validateStructure, VoiceConfig::deserialize);
        PacketRegistry.register(PacketDirection.ToServer, NetworkChannel.Default, 460, "StreamOpen", StreamOpen.class, 1, 1, false, StreamOpen::validateStructure, StreamOpen::deserialize);
        PacketRegistry.register(PacketDirection.ToClient, NetworkChannel.Default, 461, "StreamOpenResponse", StreamOpenResponse.class, 3, 16384008, false, StreamOpenResponse::validateStructure, StreamOpenResponse::deserialize);
    }

    public record PacketInfo(int id, @Nonnull String name, @Nonnull NetworkChannel channel, @Nonnull Class<? extends Packet> type, int fixedBlockSize, int maxSize, boolean compressed, @Nonnull BiFunction<ByteBuf, Integer, ValidationResult> validate, @Nonnull BiFunction<ByteBuf, Integer, Packet> deserialize) {
    }

    public static enum PacketDirection {
        ToServer,
        ToClient,
        Both;

    }
}

